Update s3.yml

diff --git a/.github/workflows/s3.yml b/.github/workflows/s3.yml
--- a/.github/workflows/s3.yml
+++ b/.github/workflows/s3.yml
@@ -36,7 +36,7 @@ jobs:
   build-and-deploy:
     runs-on: ubuntu-latest
     steps:
-    - name: Checkout Code
+    - name: Checkout
       uses: actions/checkout@v3
 
     - name: Configure AWS
@@ -46,36 +46,40 @@ jobs:
         aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
         aws-region: us-east-1
 
-    - name: Sync Files to S3
-      id: sync
+    - name: List files to deploy
+      run: find . -type f -not -path "./.git/*" > files-to-upload.txt
+
+    - name: Deploy to S3
+      id: deploy
       run: |
-        # Sync files to S3 bucket
         aws s3 sync . s3://nisheshs/ --delete --exclude ".*"
+        aws s3 ls s3://nisheshs/ --recursive > s3-files-list.txt
 
-    - name: List Uploaded Files
-      id: list
+    - name: Prepare SNS message
+      id: prepare-sns-message
       run: |
-        # List files in the S3 bucket, excluding hidden files
-        aws s3api list-objects-v2 --bucket nisheshs --query "Contents[].Key" --output text | grep -v '^\.git/' | grep -v '^\.github/' > s3-files-list.txt
-
-        # Check if files list is empty
-        if [ -s s3-files-list.txt ]; then
-          echo "Deployment succeeded.\n\nFiles uploaded to s3 bucket:\n$(cat s3-files-list.txt)" > message.txt
+        if [ $? -eq 0 ]; then
+          # Deployment succeeded
+          UPDATED_FILES=$(cat files-to-upload.txt)
+          UPLOADED_FILES=$(aws s3 ls s3://nisheshs/ --recursive --human-readable)
+          MESSAGE="Deployment succeeded.\n\nFiles uploaded to s3://nisheshs/:\n$UPLOADED_FILES"
         else
-          echo "Deployment succeeded but no files were uploaded to the S3 bucket." > message.txt
+          # Deployment failed
+          MESSAGE="Deployment failed. Please check the logs for details."
         fi
+        echo -e "$MESSAGE" > sns-message.txt
 
     - name: Notify SNS
-      if: always() # Always run this step regardless of previous steps' outcome
+      if: always() # Ensures this step runs regardless of the previous step's outcome
       run: |
         aws sns publish \
           --topic-arn arn:aws:sns:us-east-1:806395723933:notificationtopic \
-          --message file://message.txt \
-          --subject "Deployment Notification"
+          --message file://sns-message.txt
 
     - name: Send Failure Notification
-      if: failure() # Run this step only if the job fails
+      if: failure() # Runs only if the job fails
       run: |
+        echo "Deployment failed. Sending email notification..."
         aws sns publish \
           --topic-arn arn:aws:sns:us-east-1:806395723933:notificationtopic \
           --message "Deployment failed. Please check the logs for details." \
